export enum TitleAnimation {
  Title = "title",
}
export enum PlayerAnimation {
  ArrowLeft = "arrow-left",
  ArrowRight = "arrow-right",
  ArrowUp = "arrow-up",
  ArrowDown = "arrow-down",
  ArrowLeftInvincible = "arrow-left-invincible",
  ArrowRightInvincible = "arrow-right-invincible",
  ArrowUpInvincible = "arrow-up-invincible",
  ArrowDownInvincible = "arrow-down-invincible",
  KnockbackLeft = "knockback-left",
  KnockbackRight = "knockback-right",
  KnockbackUp = "knockback-up",
  KnockbackDown = "knockback-down",
  KnockbackLeftInvincible = "knockback-left-invincible",
  KnockbackRightInvincible = "knockback-right-invincible",
  KnockbackUpInvincible = "knockback-up-invincible",
  KnockbackDownInvincible = "knockback-down-invincible",
  IdleLeft = "idle-left",
  IdleRight = "idle-right",
  IdleUp = "idle-up",
  IdleDown = "idle-down",
  IdleLeftInvincible = "idle-left-invincible",
  IdleRightInvincible = "idle-right-invincible",
  IdleUpInvincible = "idle-up-invincible",
  IdleDownInvincible = "idle-down-invincible",
  SwordLeft = "sword-left",
  SwordRight = "sword-right",
  SwordUp = "sword-up",
  SwordDown = "sword-down",
  SwordLeftInvincible = "sword-left-invincible",
  SwordRightInvincible = "sword-right-invincible",
  SwordUpInvincible = "sword-up-invincible",
  SwordDownInvincible = "sword-down-invincible",
  WalkLeft = "walk-left",
  WalkRight = "walk-right",
  WalkUp = "walk-up",
  WalkDown = "walk-down",
  WalkLeftInvincible = "walk-left-invincible",
  WalkRightInvincible = "walk-right-invincible",
  WalkUpInvincible = "walk-up-invincible",
  WalkDownInvincible = "walk-down-invincible",
}
export enum MoblinAnimation {
  IdleLeft = "idle-left",
  IdleRight = "idle-right",
  IdleUp = "idle-up",
  IdleDown = "idle-down",
  IdleLeftInvincible = "idle-left-Invincible",
  IdleRightInvincible = "idle-right-Invincible",
  IdleUpInvincible = "idle-up-Invincible",
  IdleDownInvincible = "idle-down-Invincible",
}
export enum SwordAnimation {
  SwingDown1 = "swing-down-1",
  SwingDown2 = "swing-down-2",
  SwingDown3 = "swing-down-3",
  SwingLeft1 = "swing-left-1",
  SwingLeft2 = "swing-left-2",
  SwingLeft3 = "swing-left-3",
  SwingRight1 = "swing-right-1",
  SwingRight2 = "swing-right-2",
  SwingRight3 = "swing-right-3",
  SwingUp1 = "swing-up-1",
  SwingUp2 = "swing-up-2",
  SwingUp3 = "swing-up-3",
}
export enum ArrowAnimation {
  BounceLeft = "bounce-left",
  BounceRight = "bounce-right",
  BounceUp = "bounce-up",
  BounceDown = "bounce-down",
  ShootLeft = "shoot-left",
  ShootRight = "shoot-right",
  ShootUp = "shoot-up",
  ShootDown = "shoot-down",
}
